### ISSUE TITLE
Monterey login screen graphic glitches

### ISSUE THREAD

**Issue by KajtekKajtek** [sharad-paghadal/hackintosh-lenovo-m93p-sff-bigsur#1]
Hi
do you have same problems with login screen glitches?
https://www.tonymacx86.com/threads/monterey-login-screen-graphic-glitches.316782/
Thank you for any help.

**Comment by sharad-paghadal** [comment]
@KajtekKajtek I'm still using it for bigsur. I did not try monterey much!

**Comment by KajtekKajtek** [comment]
OK
I understand. Thank you.

**Comment by sharad-paghadal** [comment]
Is this repo working fine with Monterey? Let me know if you are facing any issue.
Thanks. @KajtekKajtek

**Comment by KajtekKajtek** [comment]
Yes.
Except this https://www.tonymacx86.com/threads/monterey-login-screen-graphic-glitches.316782/
